---
engines:
  duplication:
    enabled: true
    config:
      languages:
         javascript:
            mass_threshold: 70
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.module"
exclude_paths:
- config/
- test/
